[workspace]
resolver = "3"
members = ["objects_lookuper", "types", "web"]

[workspace.package]
version = "0.3.0"
edition = "2024"
license = "WTFPL"
repository = "https://github.com/sermuns/timeedit-tongs"
