[package]
name = "timeedit-tongs"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { version = "0.7.1", features = [] }
reqwest = { version = "0.13.1", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }

[features]
default = ["web"]
web = ["dioxus/web"]
